name: Random Commit Booster

on:
  schedule:
    - cron: '0 11 * * *'  # 6 AM EST
    - cron: '0 17 * * *'  # 12 PM EST
    - cron: '0 21 * * *'  # 4 PM EST
    - cron: '0 1 * * *'   # 8 PM EST
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  random-commits:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env: # Declare env vars at the job level
      GIT_USER_NAME: GitHub Action Bot
      GIT_USER_EMAIL: action@github.com

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Load Git User Config
        run: |
          if [ -f .git-user ]; then
            source .git-user
            echo "Using custom Git user config: $GIT_USER_NAME, $GIT_USER_EMAIL"
            echo "GIT_USER_NAME=$GIT_USER_NAME" >> $GITHUB_ENV
            echo "GIT_USER_EMAIL=$GIT_USER_EMAIL" >> $GITHUB_ENV
          else
            echo "No .git-user found, using defaults."
          fi

      - name: Setup Git config
        run: |
          git config --local user.name "$GIT_USER_NAME"
          git config --local user.email "$GIT_USER_EMAIL"

      - name: Add random delay before starting
        run: |
          DELAY=$(( RANDOM % 601 ))
          echo "Sleeping for $DELAY seconds to randomize commit time..."
          sleep $DELAY

      - name: Generate random commits
        run: |
          NUM_COMMITS=$(( ( RANDOM % 3 ) + 1 ))  # 1-3 commits
          echo "Generating $NUM_COMMITS commits..."

          for i in $(seq 1 $NUM_COMMITS)
          do
            echo "Commit #$i"
            echo "Random update $RANDOM at $(date)" >> update-log.txt
            git add update-log.txt
            COMMIT_MSG="Random commit $RANDOM on $(date '+%Y-%m-%d %H:%M:%S')"
            git commit -m "$COMMIT_MSG"
            SHORT_DELAY=$(( RANDOM % 31 ))
            echo "Sleeping $SHORT_DELAY seconds before next commit..."
            sleep $SHORT_DELAY
          done

      - name: Push commits
        run: |
          git push
