name: Random Commit Booster

on:
  schedule:
    - cron: '0 11 * * *'  #6am EST
    - cron: '0 17 * * *' #12pm EST
    - cron: '0 21 * * *' #4pm EST
    - cron: '0 1 * * *' #8pm EST
  
  push:
    branches:
      - main #runs after merging/pushing to main brnch
  workflow_dispatch:  #run manually

jobs:
  random-commits:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Git config
        run: |
          git config --local user.email "$GIT_USER_NAME"
          git config --local user.name "$GIT_USER_EMAIL"

      - name: Add random delay before starting
        run: |
          # Random delay: 0-600 seconds (0-10 minutes)
          DELAY=$(( RANDOM % 601 ))
          echo "Sleeping for $DELAY seconds to randomize commit time..."
          sleep $DELAY

      - name: Generate random commits
        run: |
          NUM_COMMITS=$(( ( RANDOM % 3 ) + 1 ))  # 1-3 commits
          echo "Generating $NUM_COMMITS commits..."

          for i in $(seq 1 $NUM_COMMITS)
          do
            echo "Commit #$i"
            echo "Random update $RANDOM at $(date)" >> update-log.txt
            git add update-log.txt
            COMMIT_MSG="Random commit $RANDOM on $(date '+%Y-%m-%d %H:%M:%S')"
            git commit -m "$COMMIT_MSG"
            # Add optional short delay between commits (optional: 0-30 seconds)
            SHORT_DELAY=$(( RANDOM % 31 ))
            echo "Sleeping $SHORT_DELAY seconds before next commit..."
            sleep $SHORT_DELAY
          done

      - name: Push commits
        run: |
          git push
